apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-ace-rest-ci-1
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: ace/environments/ci
    repoURL: https://github.com/sepe-gitops/multi-tenancy-gitops-apps.git
    targetRevision: new-version
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
